name: voxstruct
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg-python
  - pydub
  - librosa
  - soundfile
  - numpy
  - pandas
  - matplotlib
  - plotly
  - tqdm
  - typing-extensions
  - pytorch
  - torchaudio
  - numba
  - pip
  - pip:
    - python-dotenv==1.0.0
    - openai-whisper==20231117
    - vosk==0.3.45
    - deepspeech==0.9.3
    - deepgram-sdk==2.11.0
    - jinja2==3.1.2 